name: Ping
version: "1.2.1"
main: fr.zcraft.Ping.Ping
api-version: "1.13"

description: Useful /ping command, with lacency, TPS and diagnostic.
author: Amaury Carrade

commands:
    ping:
        description: Pong! But with latency and stuff like that.
        aliases: [lag, latency]
        permission: ping.ping
    toggleping:
        description: Displays the ping and the server load in the action bar, live-updated, to monitor performances.
        permission: ping.toggleping

permissions:
    ping.ping:
        description: Allows the usage of the /ping command.
        default: true
    ping.toggleping:
        description: Allows the usage of the /toggleping command.
        default: true
    ping.diagnostic:
        description: Allows to see diagnostics in the /ping command if the latency or server load seems to be high.
        default: true
